version: "3.8"
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB=mongodb+srv://Kesher:kesher2021@keshercluster.yxpbt.mongodb.net/Kesher?retryWrites=true&w=majority
      - TOKEN_SECRET=bec19f69f6bda4303c8a6426ae7a0ef29e940a5b7cba8ea76b0e7c44fa5490a352861050387095058f32e1d949d2c5791bbccd4602a798c3e1c4a7bd11bcf251
      - MAIL=v2u2v2u2@gmail.com
      - PASSWORD=v2chu2vh
